<img src="images/faq.png" style="float: left" />
<h1><u><b>Frequently Asked Questions</b></u></h1>
<h2>Why are we doing <i>KwaMoja</i>?</h2>
<p>I can imagine a lot of people are wondering why we are doing yet another open source ERP system. So why are we doing it?

WebERP has long been a popular ERP in developing countries as it has low a footprint and fast speed even on old hardware.However webERP has long had management issues, and many arguments on the mailing lists.

I believe to be really successful an open source project needs more openness and honesty in its management. It must try to actively encourage participation, not just at the lowest levels but all through the project. In webERP those who have disagreed have tended to get shouted down, and if they persist they have been banned from the mailing lists. Technical discussions can get heated, but are an important part of open source, and should be encouraged. If you find you have lost a discussion then you should give in gracefully and accept the general opinion. This has not been the case with webERP.

The final spark that caused us to make this fork was when the webERP admin Phil Daintree decided to claim the copyright on the whole code base for himself. We firmly believe that the copyright should belong to the individual contributors, and this will always be so on <i>KwaMoja</i>.

So what we are trying to do at <i>KwaMoja</i> is to take the good points from webERP, throw away any bad points, and look to build the project for a successful future. We plan to take any contributions to webERP and integrate them into <i>KwaMoja</i> whilst also incorporating our own new features.</p>
<img src="images/question.png" style="float: right" />
<h2>Why does www.KwaMoja.org point to www.weberp.org?</h2>
<p>Whilst we were trying to raise the funds to purchase our domain and hosting facility the administrator of the webERP project <a href="mailto:phil@logicworks.co.nz">Phil Daintree</a> decided he would use his money to take the <i>KwaMoja</i>.org domain for himself to prevent us from using it for our project. He then decided to set it to point to his own project. This appears to be his idea of building his project rather than actively developing it and we consider that his behaviour more than justifies our reasons for this fork. Fortunately a donor has stepped in and provided the funds to purchase the <i>KwaMoja</i>.com domain. We are very grateful to this benefactor who wishes not to be named here. Phil has claimed he was acting on behalf of the developers of webERP but we have yet to meet any who were consulted.</p>
<p>Amendment (2/12/2012): We now notice that Mr Daintree has changed this to point to a page of his regarding a vendetta he is waging against one of the webERP developers. We wish it to be known that we want no part in his vendettas and do not wish to be associated with it. If Mr Daintree wishes to concentrate on his vendettas we wish to concentrate on the code and making it better.</p>
<h2>Can I upgrade from webERP?</h2>
<p>Simple answer <font size="5"><b><u>Yes</u></b></font>. It is our intention to always keep data compatibility with webERP so that any user of webERP can easily upgrade to <i>KwaMoja</i>. The intention is to extend <i>KwaMoja</i> with additional functionality that webERP does not have, but to keep the existing functionality the same. We hope this makes an easy transition for everybody.</p>